Add Eth plugins blogpost
LedgerHQ/LedgerHQ.github.io pull request #28
Opened 2021-07-02 16:02 UTC by pscott

2021-07-06 09:27 UTC, lcastillo-ledger requested changes

2021-07-06 09:27 UTC, lcastillo-ledger commented on _posts/2021-01-07-ethereum-plugins.md
> +featured-img: puzzle-eth
missing corresponding pictures. Title pictures goes under assets/img/posts

2021-07-06 09:27 UTC, lcastillo-ledger commented on _includes/signatures/jean.html
> +    <img class="post-signature-prepend__picture" alt="post-signature-picture" src="/assets/img/signatures/jean.jpg" />
missing Jean's nice face :) in /assets/img/signatures/jean.jpg

2021-07-06 09:27 UTC, lcastillo-ledger commented on _posts/2021-01-07-ethereum-plugins.md
> +Unlike with Bitcoin, where most transactions are simple value transfers from an address to another, Ethereum transactions often contains interactions with `Smart Contracts`, which are programs runnin
s/from an address to another/from one address to another/
s/making compromises on its security/making compromise on its security/

2021-07-06 09:27 UTC, lcastillo-ledger commented on _posts/2021-01-07-ethereum-plugins.md
> +Until now, the device could not provide users with secure display when interacting with smart contracts. One could interact with any smart contract, but the device would just warn the user that "some
s/with secure display/with a secure display/
s/that the data was valid/the validity of said data/

2021-07-06 09:27 UTC, lcastillo-ledger commented on _posts/2021-01-07-ethereum-plugins.md
> +Plugins are small applications dedicated to parsing custom transaction fields and building a custom display to show on screen to the user. They are lightweight apps that can be installed on the deivc
s/on the deivce/on the device/
s/smart-contracts/smart contracts/ x2

2021-07-06 09:27 UTC, lcastillo-ledger commented on _posts/2021-01-07-ethereum-plugins.md
> +![compound plugin interactions schema](../assets/eth_plugins/compound-plugin-interactions-schema.png "Overview of a lending transaction processng using a plugin")
On the schema:
* Forge a transaction might not be the right word, it implies creating a fake
* Loop over ProvideParameter?
* s/Copy parameter as the amount/Copy parameter such as the amount/

2021-07-06 16:55 UTC, TamtamHero commented on _posts/2021-01-07-ethereum-plugins.md
> +![compound plugin interactions schema](../assets/eth_plugins/compound-plugin-interactions-schema.png "Overview of a lending transaction processng using a plugin")
For point 2 and 3: we're in the specific case of a Compound lending transaction: there's only 1 parameter, which is the amount

2021-07-15 12:12 UTC, pdesreux-ledger reviewed
Grammar and spell check

2021-07-15 12:12 UTC, pdesreux-ledger commented on _posts/2021-01-07-ethereum-plugins.md
> +With the release of `Ethereum app v1.8.5`, we are laying the foundation to make adding support for a full smart contract on Ledger products much easier and scalable.
```suggestion
With the release of `Ethereum app v1.8.5`, we are laying the foundation to make support addition for a full smart contract on Ledger products much easier and scalable.
```

2021-07-15 14:30 UTC, merged